### PR TITLE
add is_obstructed method and tests

### PR DESCRIPTION
**Pull request by denismartens**

### CODE REVIEW

**Comment by kenmazaika** [comment]
Nice work @denismartens!  Can you also write a test for a diagonal move that is not obstructed, to make sure that functionality works?

Also a test like this should work, but looking at your code, I believe it may not.  I think the piece at [4,4] might prove to be a false obstruction for the game because of the way you're looping through stuff.

Try to add a test like this:

```
  test "proposed move is not obstructed" do
    game = Game.create(:user_id => 1)
    game.rooks.create!(:x_axis => 4, :y_axis => 4)

    # move Pawn with the very first move of a game
    test = game.is_obstructed([3,3], [3,5])

    assert_not test
  end
```

This is one of the most challenging parts of the app, so good work, Denis!  I'm impressed with what you have so far!

**Comment by SamuelMartini** [comment]
Ok, I'm noticing that I haven't added the delegate method. So you can't call rooks on game.
Going to fix right now.
Sorry Denis

**Comment by SamuelMartini** [comment]
Done.
https://github.com/GreenMonkeys/GreenMonkeyChess/commit/56081d5f3b7b28830c5f6503987bb667368164b1

Merged with master.

**Comment by denismartens** [comment]
Hey Ken!
I thought about that one and have the "next" statement in there in case [y,x] are not along diagonal path.
Thanks for the quick fix Samuel.

**Comment by kenmazaika** [comment]
Awesome Denis.  I think you  might need to make a change to get this test to work too:

```
  test "proposed move is not obstructed for vertical" do
    game = Game.create(:user_id => 1)
    game.rooks.create!(:x_axis => 5, :y_axis => 4)

    # move Pawn with the very first move of a game
    test = game.is_obstructed([3,3], [5,5])

    assert_not test
  end
```

**Comment by denismartens** [comment]
I added some more tests to try and get every case. Looks like the method works as intended.

**Pull request merged**
