### PR TITLE
Creategametest

### PR DESCRIPTION
**Pull request by Neilda**
Finished up with the CRUD. Please review and let me know if you have any questions. Changes included are:
- Add new game
- Update game
- Delete game
- See list of available games to join
- Accessing "Join existing game" and "Create new game" in nav bar
- Added resources :games to routes.rb
- Created opponent_id to join a game
- Built form to create a new game
- Redirection to the board once game is created and game is joined

### CODE REVIEW

**Comment by waywho** [comment]
Hello, I had a look through the codes and they seem good to merge in. But I was a bit too late, now there is merge conflict. @Neilda could you resolve the conflict that so I can merge it in?

**Comment by Neilda** [comment]
O no! Ok, I'll work on it.

On Fri, Feb 27, 2015 at 4:16 PM, waywho notifications@github.com wrote:

> Hello, I had a look through the codes and they seem good to merge in. But
> I was a bit too late, now there is merge conflict. @Neilda
> https://github.com/Neilda could you resolve the conflict that so I can
> merge it in?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/GreenMonkeys/GreenMonkeyChess/pull/19#issuecomment-76497041
> .

## 

_Neilda Pacquing_
UX Designer

_Email:_ neilda@neildapacquing.com
_Skype:_ neilda.pacquing
*Portfolio: *www.neildapacquing.com
*Github: *https://github.com/Neilda  https://github.com/Neilda
*LinkedIn: *https://www.linkedin.com/in/neildapacquing

**Comment by Neilda** [comment]
Fixed it! Let's see if it merges.

**Comment by waywho** [comment]
Sorry I was really busy this weekend so didn't look at it until now. It looks like you still can't automatically merge (maybe something else got pulled it before I had a chance to do it...sorry) and Travis CI isn't not passing (something about the migration?).

**Comment by kenmazaika** [comment]
Between when you fixed the merge and now it looks like someone else merged in a change that has conflicts.  Shows the importance of getting things merged in quickly.  :)

**Pull request merged**
