### PR TITLE
Fixed populate_board to prevent a bug

### PR DESCRIPTION
**Pull request by SamuelMartini**
# **Important**

I found a bug in populate_board. 
Line 69: _self.pieces << Piece.all_. **Piece.all** add all the pieces that are present in database. This cause some bug when moving a piece and loading the board from the database. 

**What it's changed:**
Populate_board create a board of pieces without a game_id value. The game_id valued is updated when the pieces are added to game.pieces.
So now the populate_board end with: _self.pieces << Piece.where(game_id: nil)_

It should not change any of your test, but it's important that you pull this change or you are going to have bad time with the database :P

If everything seems ok, merge please.

Thanks

### CODE REVIEW

**Comment by kenmazaika** [comment]
Good catch, Samuel, but I think rather than populating the database with nil game id's and then populating it after it's saved, we should just populate the `game_id` of the piece when it's built like:

```
    @board[0][0] = Rook.create(:color => :white, :name => :rook, :position => "00", :x_axis => 0, :y_axis => 0, :game_id => self.id)
```

instead of:

```
    @board[0][0] = Rook.create(:color => :white, :name => :rook, :position => "00", :x_axis => 0, :y_axis => 0)
```

**Comment by SamuelMartini** [comment]
:+1: 
Done!

**Comment by kenmazaika** [comment]
Solid work, @SamuelMartini!  :)

**Comment by denismartens** [comment]
looks good to me, I will merge this in.

**Pull request merged**
