### PR TITLE
Initialize board. Row_system

### PR DESCRIPTION
**Pull request by SamuelMartini**
The chessboard works, but I have some problem in testing it.
The test print this output:
 No visible difference in the Array#inspect output.
 #You should look at the implementation of #== on Array or its members.

I have tried to manipulate the object in different ways but it doesn't work. Check game_test.rb 

This is the "row_system". I have builded other two that have some little differences. I'm going to pull them in a few minutes.

### CODE REVIEW

**Comment by kenmazaika** [comment]
Hey Sam -

Rule of thumb is in models you're not supposed to override the `initialize` method.  Otherwise some rails magic will break!  Also you should probably not use `attr_accessor` for the fields if you're planning on storing them in the database.

Instead of doing that call the `new` method and specify each of the details.

We can talk more about this in the call tomorrow.

**Comment by SamuelMartini** [comment]
Ok, got it!
My fault was that I first wrote the code out the app. playing just with ruby and the terminal.
Talk to you tomorrow :+1:

**Comment by SamuelMartini** [comment]
Chessboard initialized and populated.

**Comment by kenmazaika** [comment]
Hey sam, what do you think about instead of having this like this:

```
+  def board
+    @board = [["00","10","20","30","40","50","60","70"],                                                                              
+              ["01","11","21","31","41","51","61","71"],                                                              
+              ["02","12","22","32","42","52","62","72"],                  
+              ["03","13","23","33","43","53","63","73"],
+              ["04","14","24","34","44","54","64","74"],
+              ["05","15","25","35","45","55","65","75"],
+              ["06","16","26","36","46","56","66","76"],
+              ["07","17","27","37","47","57","67","77"]]
+  end
```

Initializing the board as an empty board, the loading all the pieces from database into it's corresponding position.

```
def board
return @board if @board.present?
@board = [[nil, nil, nil, nil,nil,nil,nil,nil],
 [nil, nil, nil, nil,nil,nil,nil,nil]
 [nil, nil, nil, nil,nil,nil,nil,nil]
 [nil, nil, nil, nil,nil,nil,nil,nil]
 [nil, nil, nil, nil,nil,nil,nil,nil]
 [nil, nil, nil, nil,nil,nil,nil,nil]
 [nil, nil, nil, nil,nil,nil,nil,nil]
 [nil, nil, nil, nil,nil,nil,nil,nil]]


self.pieces.each do |p|
  # figure out where in @board it should go
end
return @board
end
```

**Comment by SamuelMartini** [comment]
Yes, I like the "nil board" and actually I think is better leave the empty square as nil.

I changed the board form nil to string("00") because I liked the idea to get the axes value by pointing the string with @board[0][1][0] and @board[0][1][1]. When nil I still don't know how to get them except write, (e.g. :x_axis => 1, :y_axis => 1) and I don't know if it's ok doing this for the next step.
If it's ok, I'd go with the nil board.

**Comment by kenmazaika** [comment]
Hey Sam -

String vs. Nil is not a big deal.  I guess what I wanted to point out is that if I do:

```
g = Game.find(1)
g.board
```

The `g.board` will always be an empty board.  The instance variables won't be saved between requests. That means the method needs to populate them based on the database.

**Comment by SamuelMartini** [comment]
Ok, I got it. 
I was looking at the wrong side of the problem.
I'm going to fix that.

Thank you

**Comment by SamuelMartini** [comment]
I couldn't find a way to resolve it with that snippet. The first think that I thought it was something like @board[0] = p.where(y_axis: 0), but actually I can't call the method on it.

So this is what I accomplished so far:
https://github.com/GreenMonkeys/GreenMonkeyChess/commit/40dd9d5befb42548202148e735968b05b1c7ee95#diff-f4200b404b090a0a31241905ce7a7416

**Comment by kenmazaika** [comment]
What you have won't work once the piece gets moved.  For example:

```
r = Rook.first
r.update_attributes(:x_axis => 4, :y_axis => 4)
```

No place in the board will it populate the board with that piece, because the rook doesn't start in the position `4,4`.  You need to start with a blank `@board` and loop through every piece in the database and put it in the table; you need to split apart the "create" the thing at the initial position mentality (`populate_board`) and loading a board from the database (`board`).

Cheers,
Ken

**Comment by SamuelMartini** [comment]
Now the board method load the pieces from the database.

**Comment by kenmazaika** [comment]
Solid, @SamuelMartini!  :)

**Comment by denismartens** [comment]
Hey @SamuelMartini, @kenmazaika 

Now that we have the :type column in the pieces table, we don't need the :name column anymore, correct? Similarly, now that we have the x & y axes we don't need the :position column anymore.

**Comment by kenmazaika** [comment]
You got it, @denismartens.  That sounds right to me.

**Comment by SamuelMartini** [comment]
Yes, :position has been already removed in **move_and_capture** branch.
I'm removing :name right now, after which the branch **move_and_capture** is ready to be merged

**Pull request merged**
