### PR TITLE
Adding Travis CI yml

### PR DESCRIPTION
**Pull request by waywho**
Added a .travis.yml file to enable TravisCI for continuous integration and deployment

### CODE REVIEW

**Comment by waywho** [comment]
Hello, I am not sure what is happening. I have tried several different ways to validate/build the .travis.yml so that we can start using Travis CI to do the test, but the tests it runs on it keeps on failing and I don't know why. Is it a case of just ignore and merge the file in?

**Comment by kenmazaika** [comment]
Hey WeiHsi -

Getting Travis to work is one of the few things that I think for it to work
properly you need to push things directly to master.

Also make sure the tests all pass locally.  You may need to create a single
passing test if we don't have any real tests yet (assert true).

Feel free to modify the application, merge your own pull request, etc to
get it up and running.  This is the exception to the rule, since it's
building up testing infrastructure.

Cheers,
Ken

**Comment by SamuelMartini** [comment]
[Update]
Guys I'm trying to test a couple of data structure to model the board. 

Test unit is bullying me but in the next few hours I should pop out with something we can use. 

Samuel

**Comment by waywho** [comment]
I am sorry but I tried committing through the main branch and putting putting up a simple test but it is still throwing up errors and failed built. perhaps we could look at it tomorrow Ken. :( (pulling my hair out!)

**Comment by kenmazaika** [comment]
:)

Let's take a look tomorrow.

Cheers,
Ken

**Pull request closed without merging**
