### PR TITLE
Made a has_and_belongs_to_many change in the database.

### PR DESCRIPTION
**Pull request by Neilda**
Hey guys,

Can you check out if this made sense? I used section 2.6 of this RoR guide. http://guides.rubyonrails.org/association_basics.html.

Neilda

### CODE REVIEW

**Comment by kenmazaika** [comment]
You forgot to checkin your database migration!

**Comment by Neilda** [comment]
I just ran db:migrate and pushed it again.

**Comment by kenmazaika** [comment]
But there isn't a file located in `db/migrate/XXXXX_whatevername.rb`;  that means nobody else will get your database change.

I would say follow my answers here to drop your database:
http://www.thefirehoseproject.com/comments/846

Then regenerate a migration file and the database should be squared away!

Cheers,
Ken

**Comment by Neilda** [comment]
I followed your answers. Did it work??

**Comment by kenmazaika** [comment]
No, you still need to create the database migration file.

So long as there is not a new file in db/migrate/XXXXX_whatever.rb your change won't be valid.

**Comment by kenmazaika** [comment]
In this change though you don't have the intermediate table "games_users".  Rebuilt that table and we'll be good.

**Comment by Neilda** [comment]
I didn't add the create_table :games and :users on this table since it would create a duplication error. I'm not sure if those should have been moved to this new table.

**Comment by kenmazaika** [comment]
Awesome!  This looks better! :)

**Comment by Neilda** [comment]
Can someone please merge this into the master?

**Pull request merged**
